version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 rm s3://contact-system-frontend/next/ --recursive
      - aws s3 cp --recursive .next/standalone s3://contact-system-frontend/
      - aws cloudfront create-invalidation --distribution-id E150KDAL6JW61X --paths "/*"

artifacts:
  base-directory: .next/standalone
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'