version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - npm run export

artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/out'