version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install dependencies
      
      - npm install

  pre_build:
    commands:
      - echo Pre-build started on `date`
      # Add any environment variable setup or other pre-build steps
     

  build:
    commands:
      
      - npm run build
      npm run build
      - mkdir -p .next/standalone/.next/static
      - cp -r .next/static .next/standalone/.next/

  post_build:
    commands:
      - echo Build completed on `date`
       
artifacts:
  base-directory: frontend/.next/standalone
  files:
    - '**/*'git a
    - ../.next/static/**/*
    - ../public/**/*
  discard-paths: no

cache:
  paths:
    - 'frontend/node_modules/**/*'
    - 'frontend/.next/cache/**/*'