version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm i

  build:
    commands:
      - npm run build
      - mkdir -p .next/standalone/.next/static
      - cp -r .next/static/* .next/standalone/.next/static/
      - cp -r .next/standalone/* /tmp/
      - cp -r .next/static/* /tmp/.next/static/
      - cp -r /tmp/* .next/standalone/

artifacts:
  files:
    - '**/*'
  base-directory: .next/standalone